### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by samabsalom** [karpach/remote-shutdown-pc#1]
Hi,
Really impressed with this project it is exactly what I need. However, i have no idea how to get started. could you help, please?

Sam

**Comment by karpach** [comment]
Hi,
You can download executable from release section of the project or pull repo and build it yourself in Visual Studio 2017.

Then run executable and you will see a new icon in system tray.  Right click on it and select settings.

This will give you the ability to customize shutdown url. Open up the desired port on your router and you should be able to shut down your pc from anywhere in the world using your external IP with customized url.

**Comment by samabsalom** [comment]
thanks for helping me out! integrating it with my [https://home-assistant.io/](url) and it's perfect !

**Comment by karpach** [comment]
Sam,

Please check my other repo https://github.com/karpach/remote-controller. That program can do shutdown as well plus much more.

Viktar
