### ISSUE TITLE
Lock windows

### ISSUE THREAD

**Issue by ejordancz** [karpach/remote-shutdown-pc#10]
Hello, 
please, can you add "Lock screen". Command for this:
`Rundll32.exe user32.dll,LockWorkStation`
Also with something like this "http://remote-host-name:5001/secret/lock"
Thank you

**Comment by Shazib** [comment]
I've forked + updated this with support for locking. Have submitted a pull request but in the meantime i've put up a release
[Here](https://github.com/Shazib/remote-shutdown-pc/releases/tag/v1.1)

**Comment by karpach** [comment]
Thank you for your pull request. Unfortunately, it had some conflicts, so I manually ported lock windows changes in 1.52.
