### ISSUE TITLE
How to configure HA and the target computer?

### ISSUE THREAD

**Issue by Philou06** [karpach/remote-shutdown-pc#11]
What is the syntax to use the “Turn off screen” command please? * http://remote-host-name:5001/turnoffscreen? …/turn-off-screen? other?

Other question, do I have to open the 5001 port on my PC firewall? Because for now nothing works sadly

Is there anything to configure first in configuration.yaml to use curl commands? I have this error: Logger: homeassistant.components.command_line
Source: components/command_line/init.py:43
Integration: command_line (documentation, issues)
First occurred: 19:19:09 (2 occurrences)
Last logged: 19:20:24

Timeout for command: curl http://192.168.1.29:5001/test/turn-screen-off

Thanks for you help

**Comment by lucky3004** [comment]
I assume that you are using HomeAssistant (HA) to fire the command. So for me it works great when i use it like this in HA.

Add this to config.yaml

shell_command:
    turn_off_screen_server: 'curl http://IP:5001/TurnScreenOff/'

"change IP to your needed IP or hostname"

Restart HA and you will be able to use it as what ever you want. 

Of course you need to enable it in your firewall. I use forceshutdown to shut down the pc. You have to use TurnScreenOff instead.

**Comment by Philou06** [comment]
Hi,

Thanks for your awnser, yes I use HA to fire the command. I checked once again this morning and still doesn't work, here my configuration, I also tried to change port from 5001 to 5666 but not better:

_```
default_config:
shell_command:

# PC control
switch:
  - platform: command_line
    switches:
      pc:
        command_off: "curl http://192.168.1.29:5666/test/TurnScreenOff"
  - platform: wake_on_lan
    name: windowswol
    host: 192.168.1.29
    mac: " _myMACaddress_ "
  - platform: template
    switches:
      windows:
        value_template: "{{ states.switch.windowswol.state }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.windowswol
        turn_off:
          service: switch.turn_off
          entity_id: switch.pc
```_ 

ERROR:
ERROR (SyncWorker_8) [homeassistant.components.command_line.switch] Command failed: curl http://192.168.1.29:5666/test/TurnScreenOff

If I try this command in Terminal:
![image](https://user-images.githubusercontent.com/81933852/115208521-f0f93a00-a0fc-11eb-8fd8-7203c2b6b62a.png)

On the target PC, my firewall:
![image](https://user-images.githubusercontent.com/81933852/115208604-09695480-a0fd-11eb-817c-ba00a3544c2b.png)

![image](https://user-images.githubusercontent.com/81933852/115208685-1e45e800-a0fd-11eb-937e-72482cb10480.png)

Any idea?

**Comment by lucky3004** [comment]
Open a browser on the pc you are trying to use it and enter the website http://192.168.1.29:5666/test/TurnScreenOff to see if it is working. 
In the browser you should see "ok" and normally the screen should turn off. If this is not working you can try the command from the settings in your taskbar.

**Comment by Philou06** [comment]
Since I open in the firewall access from public area (curious because I'm in private area) I have no more errors but still doesn't work. Also tried in the browser and of course I got the answer "ok" now but it doesn't take the screen off, If I do that from taskbar settings it works

**Comment by lucky3004** [comment]
hmm. i didn't open any ports - i allowed communication for the app itself. And this for UDP and TCP. Try allowing all communication to see if it works - afterwards you can disable it again if it does work.

**Comment by Philou06** [comment]
It seems all is allowed:
![image](https://user-images.githubusercontent.com/81933852/115239115-b0aab380-a11e-11eb-9061-95cabcab5d66.png)

**Comment by Philou06** [comment]
I changed the command for shutdown and it works, perhaps the command TunOffScreen is not the right syntax?

**Comment by lucky3004** [comment]
can you try to enter the syntax all with small letters? i don't know if it is case sensitive

**Comment by lucky3004** [comment]
and this is the command that turns the screen off

                case TrayCommandType.TurnScreenOff:
                    SendMessage(
                        (IntPtr)0xffff, // HWND_BROADCAST
                        0x0112,         // WM_SYSCOMMAND
                        (IntPtr)0xf170, // SC_MONITORPOWER
                        (IntPtr)0x0002  // POWER_OFF
                    );

**Comment by lucky3004** [comment]
Great to hear. You are welcome ;-)
