### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by MBoberski** [karpach/remote-shutdown-pc#15]
I compiled app via VS 2019 without errors but when I run it the server is not created, there is no port that app is listening on. What could be the problerm, and how to debug it?

**Comment by karpach** [comment]
Hi, did you try to run the release version? I wondering if this is some kind of Firewall or antivirus issue.

**Comment by MBoberski** [comment]
Release version works fine, only compiled one do not.

W 17 czerwca 2021 16:30:59 Viktar Karpach ***@***.***> napisał:

**Comment by karpach** [comment]
I made multiple changes in the recent version. Please try to use VS2022, it should work now.
