### ISSUE TITLE
Karpach.RemoteShutdown.Controller.exe is not a valid Win32 application.

### ISSUE THREAD

**Issue by afgcons** [karpach/remote-shutdown-pc#18]
I'd like this jewel of a program to shutdown a virtualbox WinXP hosted by 64-bit Linux server. Is there a 32 bit option or version?

**Comment by karpach** [comment]
WinXP does not support .NET above 4.0 version. This program uses .NET 4.6. In general WinXP support ended on April 8, 2014.
