### ISSUE TITLE
Compile for older systems, Windows XP

### ISSUE THREAD

**Issue by jchristoffvisionary** [karpach/remote-shutdown-pc#40]
First, this is a great piece of software, super important feature for places with frequent power issues. Perhaps this is the wrong place for this question, but if someone could point me towards compiling this for old machines (they exist as VMs only now), it would be great to be able to shut them down like more modern machines.

Regards,
Jordan

**Comment by jchristoffvisionary** [comment]
Also, is it correct that this only runs for users that have installed it? I installed using one account, then logged out and in with another account and the application did not seem to be running.

Thank you.

**Comment by karpach** [comment]
I am not planning to make it compatible with Windows XP. You might be able to make the first versions compatible. The latest version relies on .NET Core.

You can run it under any account, but the auto startup will run only under the user who ran the application initially.

You can manually run the application as another user and then check / uncheck the autostart option in settings. This will update the Windows registry for the current user.
