### ISSUE TITLE
希望能运行bat批处理文件功能

### ISSUE THREAD

**Issue by RallyQ** [karpach/remote-shutdown-pc#8]
希望在命令行处能输入bat批处理文件名，手机遥控执行这个bat批处理文件。
想在休眠或关机前执行一下其他任务，我在bat中加入休眠或关机命令，
谢谢作者的小工具！

**Comment by karpach** [comment]
You can use curl or Invoke-WebRequest to make HTTP requests against the remote-shutdown application. At this point, I am not planning to add any other ways to access application.
